# Generated by Django 3.0.7 on 2020-08-01 16:06

import courses.files
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20200801_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='order',
            field=courses.files.OrderField(blank=True),
        ),
    ]
